backbone:
    name: cspdarknet
    depths: [3,9,9,3]
    input_channels: [64,128,256,512,1024] # five blocks
    output_features: [ "stage2", "stage3", "stage4" ]
    normalization: "bn"
    activation: "silu"

neck:
    # base
    depths: [3,3,3,3]
    input_channels: [256,512,1024]
    normalization: "bn"
    activation: "silu"

head:
    name: "decoupled_head"

optimizer:
    name: "SGD"
    learning_rate: 0.03
    momentum: 0.9
    weight_decay: 0.0005
    lr_scheduler: "CosineWarmupScheduler"
    warmup: 0.1
    ema: True
