# Parameters
model: "yolox"

dataset:
    format: "COCO"
    # 'D:\Code\Datasets\Detection\Steel_NEU\COCO' '/root/autodl-tmp/COCO'
    dir: 'D:\Code\Datasets\Detection\Steel_NEU\COCO'
    train: 'train'  # directory name of training image
    val: 'val'
    test: 'test'
    train_size: [224,224]  # [224,224] [416,416] [640,640]
    val_size: [224,224]
    train_batch_size: 2
    val_batch_size: 2

backbone:
    name: "cspdarknet"
    depth: 0.5
    input_channels: [32, 64, 128, 256, 512] # five blocks
    output_features: ["dark3", "dark4", "dark5"]
    normalization: "bn"
    activation: "silu"
neck:
    name: "pafpn"
    depth: 0.5
    input_channels: [128, 256, 512]
    normalization: "bn"
    activation: "silu"
head:
    name: "decoupled_head"
    classes: 6

optimizer:
    name: "SGD"
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 0.0005
    lr_scheduler: "CosineWarmupScheduler"
    warmup: 5
    ema: true

transform:
    # Train transform
    hsv_prob: 0
    flip_prob: 0.5
    # Mosaic transform
    mosaic_epoch: 280
    mosaic_prob: 1
    # Affine transform after mosaic
    degrees: 10.0
    translate: 0.1
    mosaic_scale: [0.1, 2]
    shear: 2.0
    perspective: 0.0
    # CopyPaste in mosaic
    enable_copypaste: true
    copypaste_scale: [0.5, 1.5]
    mixup_prob: 0
    cutpaste_prob: 1
    # CutOut in mosaic
    cutout_prob: 0

