# Parameters
model: "yolox"

dataset:
    format: "COCO"
    dir: 'D:\Code\Datasets\Detection\Steel_NEU\COCO'
    train: 'train'  # directory name of training image
    val: 'val'
    test: 'test'
    train_size: [416,416]  # [224,224] [416,416] [640,640]
    val_size: [416,416]
    train_batch_size: 2
    val_batch_size: 2

backbone:
    name: "cspdarknet"
    depth: 0.5
    input_channels: [32, 64, 128, 256, 512] # five blocks
    output_features: ["dark3", "dark4", "dark5"]
    normalization: "bn"
    activation: "silu"
neck:
    name: "pafpn"
    depth: 0.5
    input_channels: [128, 256, 512]
    normalization: "bn"
    activation: "silu"
head:
    name: "decoupled_head"
    classes: 6

optimizer:
    name: "SGD"
    learning_rate: 0.03
    momentum: 0.9
    weight_decay: 0.0005
    lr_scheduler: "CosineWarmupScheduler"
    warmup: 5
    ema: false

transform:
    mosaic_epoch: 150
