backbone:
    name: eelan
    depths: [2,2,2,2]
    channels: [32,64,128,256,512] # five blocks
    outputs: [ "stage2", "stage3", "stage4" ]
    norm: bn
    act: lrelu

neck:
    name: yolov7neck
    depths: [2,2,2,2]
    channels: [256, 512, 512]
    norm: bn
    act: lrelu

head:
    name: implicit_head
    num_class: 6
    num_anchor: 3
    channels: [128, 256, 512]
    norm: bn
    act: lrelu

loss:
    name: yolov7
    num_class: 6
    stride: [8,16,32]
    anchors:
        - [ [ 98,37 ], [ 624,16 ], [ 316,41 ] ]  # P3/8
        - [ [ 642,29 ], [ 640,43 ], [ 639,84 ] ]  # P4/16
        - [ [ 634,114 ], [ 639,153 ], [ 644,217 ] ]  # P5/32

optimizer:
    name: "SGD"
    learning_rate: 0.03
    momentum: 0.9
    weight_decay: 0.0005
    lr_scheduler: "CosineWarmupScheduler"
    warmup: 0.1
    ema: True
