# Parameters
model: "yolov5"

dataset:
    format: "COCO"
    dir: '/root/autodl-tmp/COCO'
    train: 'train'  # directory name of training image
    val: 'val'
    test: 'test'
    train_size: [640,640]   # [224,224] [416,416] [640,640]
    val_size: [640,640]
    train_batch_size: 32
    val_batch_size: 32

backbone:
    name: "cspdarknet"
    depth: 0.5
    input_channels: [32, 64, 128, 256, 512] # five blocks
    output_features: ["dark3", "dark4", "dark5"]
    normalization: "bn"
    activation: "silu"
neck:
    name: "pafpn"
    depth: 0.5
    input_channels: [128, 256, 512]
    normalization: "bn"
    activation: "silu"
head:
    name: "decoupled_head"
    classes: 6
    anchors:
      - [ [10,13], [16,30], [33,23] ]  # P3/8
      - [ [30,61], [62,45], [59,119] ]  # P4/16
      - [ [116,90], [156,198], [373,326] ]  # P5/32

optimizer:
    name: "SGD"
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 0.0005
    lr_scheduler: "CosineWarmupScheduler"
    warmup: 5
    ema: false

transform:
    mosaic_epoch: 150
