backbone:
    name: cspdarknet
    depths: [2,6,6,2]
    channels: [48,96,192,384,768] # five blocks
    outputs: [ "stage2", "stage3" ]
    norm: bn
    act: silu
    weights: yolox608-idd-sunny.pt

neck:
    null

head:
    name: decoupled_head
    num_class: 10
    num_anchor: 1
    channels: [256, 512]
    norm: bn
    act: silu

loss:
    name: yolox
    num_class: 15
    stride: [8, 16]

optimizer:
    name: "SGD"
    learning_rate: 0.0001
    momentum: 0.9
    weight_decay: 0.0005
    lr_scheduler: "CosineWarmupScheduler"
    warmup: 0.1
    ema: False
