backbone:
    name: cspdarknet
    depths: [2,6,6,2]
    channels: [48,96,192,384,768] # five blocks
    outputs: [ "stage3" ]
    norm: bn
    act: silu
    weights: ayolox320-full-sunny.pt

neck:
    null

head:
    name: decoupled_head
    num_class: 10
    num_anchor: 1
    channels: [384]
    norm: bn
    act: silu

loss:
    name: yolox
    num_class: 10
    stride: [16]

optimizer:
    name: "SGD"
    learning_rate: 0.03
    momentum: 0.9
    weight_decay: 0.0005
    lr_scheduler: "CosineWarmupScheduler"
    warmup: 0.1
    ema: True
