# Parameters
datamodule: 'coco'
model: 'yolox'

dataset:
    format: "COCO"
    dir: 'F:\Code\Datasets\Detection\NEU_DET\COCO'
    num_classes: 6
    train: 'train'  # directory name of training image
    val: 'val'
    test: 'test'
    train_size: [224,224]  # [224,224] [416,416] [640,640]
    val_size: [224,224]
    train_batch_size: 16
    val_batch_size: 1

backbone:
    # CSPDarkNet
    depths: [ 2,6,6,2 ]
    input_channels: [48,96,192,384,768]
    output_features: [ "stage2", "stage3", "stage4" ]
    normalization: "bn"
    activation: "silu"

neck:
    # PAFPN
    depths: [ 2,2,2,2 ]
    input_channels: [192,384,768]
    normalization: "bn"
    activation: "silu"

head:
    name: "decoupled_head"

optimizer:
    name: "SGD"
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 0.0005
    lr_scheduler: "CosineWarmupScheduler"
    warmup: 0.1
    ema: True

transform:
    # Train transform
    hsv_prob: 0.5
    flip_prob: 0.5
    # Mosaic transform
    mosaic_prob: 0.9
    mosaic_scale: [ 0.1, 2.0 ]
    # Affine transform after mosaic
    degrees: 0
    translate: 0.1
    shear: 2.0
    perspective: 0.0
    # CopyPaste in mosaic
    copypaste_prob: 0
    copypaste_scale: [ 0.5, 1.5 ]
    # CutPaste in mosaic
    cutpaste_prob: 0
    # Cutout rounding background
    cutoutR_prob: 0.5
