# Parameters


CSPDARKNET:
    DEPTH: 0.5
    INPUT_CHANNELS: [32, 64, 128, 256, 512] # five blocks
    OUT_FEATURES: ["dark3", "dark4", "dark5"]
    NORM: "bn"
    ACT: "silu"
PAFPN:
    DEPTH: 0.5
    INPUT_CHANNELS: [128, 256, 512]
    NORM: "bn"
    ACT: "silu"
YOLOXHEAD:
    CLASSES: 6

DATASET:
    DIR: '/root/autodl-tmp/COCO'
    TRAIN_JSON: 'train.json'
    VAL_JSON: 'val.json'
    TEST_JSON: 'val.json'
    TRAIN_SIZE: [ 416,416 ]
    VAL_SIZE: [ 416,416 ]
    TRAIN_BATCH_SIZE: 32
    VAL_BATCH_SIZE: 32
