# Parameters


CSPDARKNET:
    DEPTH: 0.5
    INPUT_CHANNELS: [32, 64, 128, 256, 512] # five blocks
    OUT_FEATURES: ["dark3", "dark4", "dark5"]
    NORM: "bn"
    ACT: "silu"
PAFPN:
    DEPTH: 0.5
    INPUT_CHANNELS: [128, 256, 512]
    NORM: "bn"
    ACT: "silu"
YOLOXHEAD:
    CLASSES: 6

DATASET:
    DIR: 'D:\Code\Datasets\Detection\Steel_NEU\COCO'
    TRAIN_JSON: 'train.json'
    VAL_JSON: 'val.json'
    TEST_JSON: 'test.json'
    TRAIN_SIZE: [224,224]
    TEST_SIZE: [224,224]
