# Parameters

CSPDARKNET:
    DEPTH: 0.5
    INPUT_CHANNELS: [64, 128, 256, 512, 1024] # five blocks
    OUT_FEATURES: ["dark3", "dark4", "dark5"]
    NORM: "bn"
    ACT: "silu"
PAFPN:
    DEPTH: 0.5
    INPUT_CHANNELS: [256, 512, 1024]
    NORM: "bn"
    ACT: "silu"
YOLOXHEAD:
    CLASSES: 6

DATASET:
    DIR: 'D:\Code\Datasets\Detection\Steel_NEU\COCO'
    TRAIN_JSON: 'train.json'
    VAL_JSON: 'val.json'
    TEST_JSON: 'test.json'
    TRAIN_SIZE: [224,224]
    VAL_SIZE: [224,224]
    TRAIN_BATCH_SIZE: 16
    VAL_BATCH_SIZE: 16
