# Parameters

backbone:
    name: "cspdarknet"
    depth: 0.5
    input_channels: [32, 64, 128, 256, 512] # five blocks
    output_features: ["dark3", "dark4", "dark5"]
    normalization: "bn"
    activation: "silu"
neck:
    name: "pafpn"
    depth: 0.5
    input_channels: [128, 256, 512]
    normalization: "bn"
    activation: "silu"
head:
    name: "decoupled_head"
    classes: 6

dataset:
    dir: '/content/drive/MyDrive/COCO'
    train: 'train'  # directory name of training image
    val: 'val'
    test: 'test'
    TRAIN_SIZE: [224,224]
    VAL_SIZE: [224,224]
    TRAIN_BATCH_SIZE: 64
    VAL_BATCH_SIZE: 64

transform:
    mosaic_epoch: 200

