# Parameters

backbone:
    name: "cspdarknet"
    depth: 0.5
    input_channels: [32, 64, 128, 256, 512] # five blocks
    output_features: ["dark3", "dark4", "dark5"]
    normalization: "bn"
    activation: "silu"
neck:
    name: "pafpn"
    depth: 0.5
    input_channels: [128, 256, 512]
    normalization: "bn"
    activation: "silu"
head:
    name: "decoupled_head"
    classes: 6

dataset:
    format: "COCO"
    dir: 'D:\Code\Datasets\Detection\Steel_NEU\COCO'
    train: 'train'  # directory name of training image
    val: 'val'
    test: 'test'
    train_size: [224,224]
    val_size: [224,224]
    train_batch_size: 4
    val_batch_size: 4

transform:
    mosaic_epoch: 50
