backbone:
    name: swin_transformer
    embed_dim: 128
    depths: [2, 2, 18, 2]
    num_heads: [4, 8, 16, 32]
    window_size: 7
    mlp_ratio: 4.
    drop_path_rate: 0.5

neck:
    name: none

head:
    name: decoupled_head
    num_anchor: 1
    channels: [128, 256, 512, 1024]
    norm: bn
    act: silu

loss:
    name: yolox
    stride: [4,8,16,32]

optimizer:
    name: "SGD"
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 0.0005
    lr_scheduler: "CosineWarmupScheduler"
    warmup: 0.1
    ema: True
