# Parameters
datamodule: 'neu-det'
model: 'yolox'

dataset:
    format: "COCO"
    dir: 'F:\Code\Datasets\Detection\Aluminium\COCO'
    num_classes: 7
    train: 'train'  # directory name of training image
    val: 'val'
    test: 'test'
    train_size: [ 640,640 ]  # [224,224] [416,416] [640,640]
    val_size: [ 640,640 ]
    train_batch_size: 1
    val_batch_size: 1

backbone:
    # base
    depths: [ 3,9,9,3 ]
    input_channels: [ 32, 64, 128, 256, 512 ] # five blocks
    output_features: [ "stage2", "stage3", "stage4" ]
    normalization: "bn"
    activation: "silu"

    # ResNet
    block: "BasicBlock"  # BottleNeck

    # ConvNext
    drop_path_rate: 0.0
    layer_scale_init_value: 0.000001

    # Swim
    patch_size: [ 4, 4 ]
    embed_dim: 96
    num_heads: [ 3, 6, 12, 24 ]

neck:
    # base
    depths: [ 1,1,1,1 ]
    input_channels: [ 128, 256, 512 ]
    normalization: "bn"
    activation: "silu"

head:
    name: "decoupled_head"

optimizer:
    name: "SGD"
    learning_rate: 0.03
    momentum: 0.9
    weight_decay: 0.0005
    lr_scheduler: "CosineWarmupScheduler"
    warmup: 0.1
    ema: True

transform:
    # Train transform
    hsv_prob: 0.5
    flip_prob: 0.5
    # Mosaic transform
    mosaic_prob: 0.9
    mosaic_scale: [ 0.1, 2.0 ]
    # Affine transform after mosaic
    degrees: 0
    translate: 0.1
    shear: 2.0
    perspective: 0.0
    # CopyPaste in mosaic
    copypaste_prob: 0
    copypaste_scale: [ 0.5, 1.5 ]
    # CutPaste in mosaic
    cutpaste_prob: 0
    # Cutout rounding background
    cutoutR_prob: 0.5


