model: 'yolox'

backbone:
    name: shufflenetv2
    channels: [36, 104, 208, 416] # four blocks
    outputs: [ "stage2", "stage3", "stage4" ]
    norm: bn
    act: silu

neck:
    name: none

head:
    name: decoupled_head
    num_class: 6
    num_anchor: 1
    channels: [104, 208, 416]
    norm: bn
    act: silu

loss:
    name: yolox
    num_class: 6
    stride: [8,16,32]

optimizer:
    name: "SGD"
    learning_rate: 0.03
    momentum: 0.9
    weight_decay: 0.0005
    lr_scheduler: "CosineWarmupScheduler"
    warmup: 0.1
    ema: True
