datamodule: 'neu-det'

dataset:
    format: "COCO"
    dir: '../AL_COCO'
    num_classes: 6
    train: 'train'  # directory name of training image
    val: 'val'
    test: 'test'
    train_size: [640,640]
    val_size: [640,640]
    train_batch_size: 8
    val_batch_size: 1

transform:
    # Train transform
    hsv_prob: 0.5
    flip_prob: 0.5
    # Mosaic transform
    mosaic_prob: 0.9
    mosaic_scale: [ 0.1, 2.0 ]
    # Affine transform after mosaic
    degrees: 0
    translate: 0.1
    shear: 2.0
    perspective: 0.0
    # CopyPaste in mosaic
    copypaste_prob: 0
    copypaste_scale: [ 0.5, 1.5 ]
    # CutPaste in mosaic
    cutpaste_prob: 0
    # Cutout rounding background
    cutoutR_prob: 0
